### ISSUE TITLE
Duplicate instances (Lift Text Text added to text 1.2.4.0)

### ISSUE THREAD

**Issue by oliver-batchelor** [bennofs/th-lift-instances#15]
This just started popping up, text-1.2.4.0 seems like the culprit?

src/Instances/TH/Lift.hs:141:10: error:
    Duplicate instance declarations:
      instance Lift Text.Text
        -- Defined at src/Instances/TH/Lift.hs:141:10
      instance Lift Text.Text -- Defined in ‘Data.Text’
    |
141 | instance Lift Text.Text where
    |          ^^^^^^^^^^^^^^

src/Instances/TH/Lift.hs:144:10: error:
    Duplicate instance declarations:
      instance Lift Text.Lazy.Text
        -- Defined at src/Instances/TH/Lift.hs:144:10
      instance Lift Text.Lazy.Text -- Defined in ‘Data.Text.Lazy’

**Comment by bennofs** [comment]
Fixed in 75d2444ce12c2a86e15fdd1b163ce514c7d558e1, releasing when build is green

**Comment by vmchale** [comment]
Package bounds are still wrong: https://matrix.hackage.haskell.org/#/package/th-lift-instances/0.1.13/ghc-8.2.2@1565727228

**Comment by phadej** [comment]
I made necessary revisions
